package schema

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/JiangHe12/opskit-core/v2/apperrors"
)

func TestParseCreateTablesMinimal(t *testing.T) {
	got, err := ParseDesiredSQL(`
CREATE TABLE users (
  id BIGINT,
  name VARCHAR(100),
  created_at DATETIME
);
`)
	if err != nil {
		t.Fatalf("ParseDesiredSQL() error = %v", err)
	}
	users, ok := got.Tables["users"]
	if !ok {
		t.Fatalf("users table missing: %+v", got)
	}
	if len(users.Columns) != 3 || users.Columns[1].Name != "name" || users.Columns[1].Type != "VARCHAR(100)" {
		t.Fatalf("columns = %+v", users.Columns)
	}
}

func TestParseCreateTableAcceptsPostgresQuotedIdentifiers(t *testing.T) {
	got, err := ParseDesiredSQL(`CREATE TABLE "evil"";--" ("id"";--" integer NOT NULL, "name" text DEFAULT 'x', CONSTRAINT "evil_pkey" PRIMARY KEY ("id"";--"));`)
	if err != nil {
		t.Fatalf("ParseDesiredSQL() error = %v", err)
	}
	table, ok := got.Tables[`evil";--`]
	if !ok {
		t.Fatalf("quoted table missing: %+v", got.Tables)
	}
	if len(table.Columns) != 2 || table.Columns[0].Name != `id";--` || table.Columns[0].Type != "integer" || table.Columns[1].Name != "name" || table.Columns[1].Type != "text" {
		t.Fatalf("columns = %+v", table.Columns)
	}
}

func TestParseCreateTableAcceptsOnlyFixedPublicSchemaQualifier(t *testing.T) {
	for _, sqlText := range []string{
		`CREATE TABLE "public"."users" ("id" integer);`,
		`CREATE TABLE PUBLIC.users (id integer);`,
	} {
		got, err := ParseDesiredSQL(sqlText)
		if err != nil {
			t.Fatalf("ParseDesiredSQL(%q) error = %v", sqlText, err)
		}
		if _, ok := got.Tables["users"]; !ok {
			t.Fatalf("qualified users table missing: %+v", got.Tables)
		}
	}
	for _, sqlText := range []string{
		`CREATE TABLE "other"."users" ("id" integer);`,
		`CREATE TABLE "PUBLIC"."users" ("id" integer);`,
		`CREATE TABLE public.other.users (id integer);`,
	} {
		if _, err := ParseDesiredSQL(sqlText); err == nil {
			t.Fatalf("ParseDesiredSQL(%q) error = nil, want non-public qualifier rejection", sqlText)
		}
	}
}

func TestParseCreateTableCapturesMultiWordTypes(t *testing.T) {
	got, err := ParseDesiredSQL(`CREATE TABLE "metrics" (
  "name" character varying(255),
  "created_at" timestamp with time zone,
  "amount" numeric(10,2),
  "ratio" double precision,
  "open_at" time without time zone,
  "count" integer NOT NULL,
  "flags" int unsigned,
  "label" varchar(50)
);`)
	if err != nil {
		t.Fatalf("ParseDesiredSQL() error = %v", err)
	}
	columns := got.Tables["metrics"].Columns
	want := map[string]string{
		"name":       "character varying(255)",
		"created_at": "timestamp with time zone",
		"amount":     "numeric(10,2)",
		"ratio":      "double precision",
		"open_at":    "time without time zone",
		"count":      "integer",
		"flags":      "int unsigned",
		"label":      "varchar(50)",
	}
	if len(columns) != len(want) {
		t.Fatalf("columns = %+v", columns)
	}
	for _, column := range columns {
		if column.Type != want[column.Name] {
			t.Fatalf("column %s type = %q, want %q; columns=%+v", column.Name, column.Type, want[column.Name], columns)
		}
	}
}

func TestParseCreateTableCapturesAutoIncrement(t *testing.T) {
	got, err := ParseDesiredSQL(`CREATE TABLE "ids" (
  "serial_id" serial PRIMARY KEY,
  "bigserial_id" bigserial NOT NULL,
  "smallserial_id" smallserial,
  "identity_default" integer GENERATED BY DEFAULT AS IDENTITY,
  "identity_always" bigint GENERATED ALWAYS AS IDENTITY,
  ` + "`mysql_id`" + ` int AUTO_INCREMENT,
  "plain" integer NOT NULL
);`)
	if err != nil {
		t.Fatalf("ParseDesiredSQL() error = %v", err)
	}
	columns := got.Tables["ids"].Columns
	want := map[string]struct {
		columnType    string
		autoIncrement bool
	}{
		"serial_id":        {columnType: "integer", autoIncrement: true},
		"bigserial_id":     {columnType: "bigint", autoIncrement: true},
		"smallserial_id":   {columnType: "smallint", autoIncrement: true},
		"identity_default": {columnType: "integer", autoIncrement: true},
		"identity_always":  {columnType: "bigint", autoIncrement: true},
		"mysql_id":         {columnType: "int", autoIncrement: true},
		"plain":            {columnType: "integer", autoIncrement: false},
	}
	for _, column := range columns {
		expected, ok := want[column.Name]
		if !ok {
			t.Fatalf("unexpected column %+v", column)
		}
		if column.Type != expected.columnType || column.AutoIncrement != expected.autoIncrement {
			t.Fatalf("column %s = type %q auto %t, want type %q auto %t", column.Name, column.Type, column.AutoIncrement, expected.columnType, expected.autoIncrement)
		}
	}
}

func TestSchemaRoundTripPreservesPostgresAndMySQLTypes(t *testing.T) {
	current := Schema{Tables: map[string]Table{
		"metrics": {
			Name: "metrics",
			Columns: []Column{
				{Name: "name", Type: "character varying(255)"},
				{Name: "created_at", Type: "timestamp with time zone"},
				{Name: "amount", Type: "numeric(10,2)"},
				{Name: "ratio", Type: "double precision"},
				{Name: "open_at", Type: "time without time zone"},
				{Name: "id", Type: "int"},
				{Name: "label", Type: "varchar(50)"},
				{Name: "flags", Type: "int unsigned"},
			},
		},
	}}
	desired, err := ParseDesiredSQL(`CREATE TABLE "metrics" (
  "name" character varying(255),
  "created_at" timestamp with time zone,
  "amount" numeric(10,2),
  "ratio" double precision,
  "open_at" time without time zone,
  "id" int,
  "label" varchar(50),
  "flags" int unsigned
);`)
	if err != nil {
		t.Fatalf("ParseDesiredSQL() error = %v", err)
	}
	if diff := Diff(current, desired); len(diff.Changes) != 0 {
		t.Fatalf("Diff() changes = %+v, want none", diff.Changes)
	}
}

func TestDiffDetectsAutoIncrementChanges(t *testing.T) {
	current := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "id", Type: "integer"}}},
	}}
	desired := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "id", Type: "integer", AutoIncrement: true}}},
	}}
	diff := Diff(current, desired)
	if len(diff.Changes) != 1 {
		t.Fatalf("changes = %+v, want 1", diff.Changes)
	}
	change := diff.Changes[0]
	if change.Action != ActionModifyColumn || change.Column != "id" || change.Type != "integer" || !change.AutoIncrement || !change.AutoIncrementChanged || change.TypeChanged {
		t.Fatalf("auto increment change = %+v", change)
	}
}

func TestDiffCarriesAutoIncrementIndexContext(t *testing.T) {
	current := Schema{Tables: map[string]Table{
		"users": {
			Name:    "users",
			Columns: []Column{{Name: "id", Type: "BIGINT", Key: "PRI"}, {Name: "seq", Type: "int"}},
			Indexes: []Index{{Name: "PRIMARY", Columns: []string{"id"}, Unique: true}},
		},
	}}
	desired := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}, {Name: "seq", Type: "int", AutoIncrement: true}, {Name: "new_seq", Type: "int", AutoIncrement: true}}},
	}}

	diff := Diff(current, desired)
	if len(diff.Changes) != 2 {
		t.Fatalf("changes = %+v, want 2", diff.Changes)
	}
	if diff.Changes[0].Action != ActionModifyColumn || diff.Changes[0].Column != "seq" || !diff.Changes[0].AutoIncrementIndexRequired {
		t.Fatalf("modify autoincrement change = %+v, want index required", diff.Changes[0])
	}
	if diff.Changes[1].Action != ActionAddColumn || diff.Changes[1].Column != "new_seq" || !diff.Changes[1].AutoIncrementIndexRequired {
		t.Fatalf("add autoincrement change = %+v, want index required", diff.Changes[1])
	}
}

func TestDiffSkipsAutoIncrementIndexWhenColumnAlreadyIndexed(t *testing.T) {
	current := Schema{Tables: map[string]Table{
		"users": {
			Name:    "users",
			Columns: []Column{{Name: "seq", Type: "int", Key: "MUL"}},
			Indexes: []Index{{Name: "idx_users_seq", Columns: []string{"seq"}, Unique: false}},
		},
	}}
	desired := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "seq", Type: "int", AutoIncrement: true}}},
	}}

	diff := Diff(current, desired)
	if len(diff.Changes) != 1 {
		t.Fatalf("changes = %+v, want 1", diff.Changes)
	}
	if diff.Changes[0].AutoIncrementIndexRequired {
		t.Fatalf("change = %+v, want no extra index for indexed column", diff.Changes[0])
	}
}

func TestParseCreateTablesRejectsUnsupportedDDL(t *testing.T) {
	_, err := ParseDesiredSQL(`ALTER TABLE users ADD COLUMN age INT;`)
	if err == nil {
		t.Fatal("ParseDesiredSQL() error = nil, want unsupported DDL error")
	}
	if got := apperrors.AsAppError(err).Code; got != apperrors.CodeNotImplemented {
		t.Fatalf("error code = %s, want %s; err = %v", got, apperrors.CodeNotImplemented, err)
	}
}

func TestParseCreateTableRejectsTrailingAndTypeStatementInjection(t *testing.T) {
	tests := []struct {
		name string
		sql  string
	}{
		{
			name: "second ddl statement",
			sql:  "CREATE TABLE harmless (id INT); DROP TABLE critical; -- )",
		},
		{
			name: "second ddl after carriage return comment",
			sql:  "CREATE TABLE harmless (id INT) -- hidden\r; DROP TABLE critical",
		},
		{
			name: "column type statement separator",
			sql:  "CREATE TABLE harmless (id integer; DROP TABLE critical)",
		},
		{
			name: "ddl disguised as table option",
			sql:  "CREATE TABLE harmless (id integer) DROP TABLE critical",
		},
		{
			name: "ambiguous backslash escaped type quote",
			sql:  `CREATE TABLE harmless (payload "safe\"; DROP TABLE critical; --")`,
		},
		{
			name: "postgres alter type using clause",
			sql:  "CREATE TABLE harmless (payload integer USING pg_sleep(1))",
		},
		{
			name: "mysql first position clause",
			sql:  "CREATE TABLE harmless (payload integer FIRST)",
		},
		{
			name: "mysql after position clause",
			sql:  "CREATE TABLE harmless (payload integer AFTER other)",
		},
		{
			name: "mysql hash comment in type",
			sql:  "CREATE TABLE harmless (payload integer # hidden modifier)",
		},
		{
			name: "mysql hash comment after constraint",
			sql:  "CREATE TABLE harmless (payload integer DEFAULT 1 # hidden modifier)",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := ParseDesiredSQL(tt.sql); err == nil {
				t.Fatalf("ParseDesiredSQL(%q) error = nil, want fail-closed rejection", tt.sql)
			}
		})
	}
}

func TestParseCreateTableAcceptsSafeMySQLTailAndQuotedTypeValues(t *testing.T) {
	got, err := ParseDesiredSQL(`CREATE TABLE events (
	  kind enum('created;ok','C:\\path'),
	  path varchar(255) DEFAULT 'C:\\tmp'
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`)
	if err != nil {
		t.Fatalf("ParseDesiredSQL() error = %v", err)
	}
	columns := got.Tables["events"].Columns
	if len(columns) != 2 || columns[0].Type != `enum('created;ok','C:\\path')` || columns[1].Type != "varchar(255)" {
		t.Fatalf("columns = %+v", columns)
	}
}

func TestDiffSchemaFindsAddAndDropColumns(t *testing.T) {
	current := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}, {Name: "legacy", Type: "TEXT"}}},
	}}
	desired := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}, {Name: "name", Type: "VARCHAR(100)"}}},
	}}

	diff := Diff(current, desired)
	if len(diff.Changes) != 2 {
		t.Fatalf("changes = %+v, want 2", diff.Changes)
	}
	if diff.Changes[0].Action != ActionAddColumn || diff.Changes[0].Column != "name" || diff.Changes[0].Destructive {
		t.Fatalf("add change = %+v", diff.Changes[0])
	}
	if diff.Changes[1].Action != ActionDropColumn || diff.Changes[1].Column != "legacy" || !diff.Changes[1].Destructive {
		t.Fatalf("drop change = %+v", diff.Changes[1])
	}
	if !diff.Destructive {
		t.Fatal("DiffResult.Destructive = false, want true")
	}
}

func TestDiffSchemaFindsModifyColumnAndCreateTable(t *testing.T) {
	current := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}, {Name: "name", Type: "VARCHAR(100)"}}},
	}}
	desired := Schema{Tables: map[string]Table{
		"users":  {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}, {Name: "name", Type: "TEXT"}}},
		"orders": {Name: "orders", Columns: []Column{{Name: "id", Type: "BIGINT"}, {Name: "user_id", Type: "BIGINT"}}},
	}}

	diff := Diff(current, desired)
	if len(diff.Changes) != 2 {
		t.Fatalf("changes = %+v, want 2", diff.Changes)
	}
	if diff.Changes[0].Action != ActionCreateTable || diff.Changes[0].Table != "orders" || len(diff.Changes[0].Columns) != 2 {
		t.Fatalf("create table change = %+v", diff.Changes[0])
	}
	if diff.Changes[1].Action != ActionModifyColumn || diff.Changes[1].Column != "name" || diff.Changes[1].Type != "TEXT" || !diff.Changes[1].TypeChanged || !diff.Changes[1].Destructive {
		t.Fatalf("modify column change = %+v", diff.Changes[1])
	}
	if !diff.Destructive {
		t.Fatal("DiffResult.Destructive = false, want true")
	}
}

func TestDiffSchemaWarnsAboutPossibleRename(t *testing.T) {
	current := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}, {Name: "legacy", Type: "TEXT"}}},
	}}
	desired := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}, {Name: "display_name", Type: "TEXT"}}},
	}}

	diff := Diff(current, desired)
	if len(diff.Warnings) != 1 || diff.Warnings[0] == "" {
		t.Fatalf("warnings = %+v, want possible rename warning", diff.Warnings)
	}
	if diff.Changes[1].Action != ActionDropColumn || !diff.Changes[1].Destructive {
		t.Fatalf("drop side of possible rename = %+v", diff.Changes[1])
	}
}

func TestDiffDoesNotDropTablesMissingFromDesired(t *testing.T) {
	current := Schema{Tables: map[string]Table{
		"users":  {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}}},
		"orders": {Name: "orders", Columns: []Column{{Name: "id", Type: "BIGINT"}}},
	}}
	desired := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}}},
	}}

	diff := Diff(current, desired)
	for _, change := range diff.Changes {
		if change.Action == ActionDropTable {
			t.Fatalf("Diff produced DROP_TABLE for missing desired table: %+v", diff.Changes)
		}
	}
}

func TestExtraTablesAndPruneChanges(t *testing.T) {
	current := Schema{Tables: map[string]Table{
		"users":  {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}}},
		"orders": {Name: "orders", Columns: []Column{{Name: "id", Type: "BIGINT"}}},
		"logs":   {Name: "logs", Columns: []Column{{Name: "id", Type: "BIGINT"}}},
	}}
	desired := Schema{Tables: map[string]Table{
		"users": {Name: "users", Columns: []Column{{Name: "id", Type: "BIGINT"}}},
	}}

	extra := ExtraTables(current, desired)
	if len(extra) != 2 || extra[0] != "logs" || extra[1] != "orders" {
		t.Fatalf("ExtraTables() = %+v, want sorted logs/orders", extra)
	}
	prune := PruneChanges(current, desired)
	if len(prune) != 2 {
		t.Fatalf("PruneChanges() = %+v, want 2", prune)
	}
	for i, name := range extra {
		if prune[i].Action != ActionDropTable || prune[i].Table != name || !prune[i].Destructive {
			t.Fatalf("prune[%d] = %+v, want DROP_TABLE %s destructive", i, prune[i], name)
		}
	}
}

func TestLoadDesiredDirMergesSQLFiles(t *testing.T) {
	dir := t.TempDir()
	writeSchemaTestFile(t, dir, "users.sql", "CREATE TABLE users (id BIGINT);")
	writeSchemaTestFile(t, dir, "orders.sql", "CREATE TABLE orders (id BIGINT, user_id BIGINT);")
	writeSchemaTestFile(t, dir, "notes.txt", "ignored")

	got, err := LoadDesiredDir(dir)
	if err != nil {
		t.Fatalf("LoadDesiredDir() error = %v", err)
	}
	if len(got.Tables) != 2 || got.Tables["users"].Name != "users" || got.Tables["orders"].Name != "orders" {
		t.Fatalf("schema = %+v", got)
	}
}

func TestLoadDesiredDirRejectsDuplicateTablesAndEmptyDirs(t *testing.T) {
	dup := t.TempDir()
	writeSchemaTestFile(t, dup, "users.sql", "CREATE TABLE users (id BIGINT);")
	writeSchemaTestFile(t, dup, "also_users.sql", "CREATE TABLE users (name TEXT);")
	if _, err := LoadDesiredDir(dup); err == nil {
		t.Fatal("expected duplicate table error")
	} else if got := apperrors.AsAppError(err).Code; got != apperrors.CodeValidationFailed {
		t.Fatalf("duplicate error code = %s, want %s", got, apperrors.CodeValidationFailed)
	}

	empty := t.TempDir()
	if _, err := LoadDesiredDir(empty); err == nil {
		t.Fatal("expected empty directory error")
	} else if got := apperrors.AsAppError(err).Code; got != apperrors.CodeValidationFailed {
		t.Fatalf("empty error code = %s, want %s", got, apperrors.CodeValidationFailed)
	}
}

func TestParseCreateTableColumnErrorCodes(t *testing.T) {
	tests := []struct {
		name string
		sql  string
		code apperrors.ErrorCode
	}{
		{name: "unsupported column definition", sql: "CREATE TABLE users (id);", code: apperrors.CodeNotImplemented},
		{name: "no columns", sql: "CREATE TABLE users (PRIMARY KEY (id));", code: apperrors.CodeValidationFailed},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseDesiredSQL(tc.sql)
			if got := apperrors.AsAppError(err).Code; got != tc.code {
				t.Fatalf("error code = %s, want %s; err = %v", got, tc.code, err)
			}
		})
	}
}

func TestSchemaFromDDLMapMergesTablesAndRejectsInvalidInput(t *testing.T) {
	got, err := SchemaFromDDLMap(map[string]string{
		"users":  "CREATE TABLE users (id BIGINT);",
		"orders": "CREATE TABLE orders (id BIGINT, user_id BIGINT);",
	})
	if err != nil {
		t.Fatalf("SchemaFromDDLMap() error = %v", err)
	}
	if len(got.Tables) != 2 || got.Tables["orders"].Columns[1].Name != "user_id" {
		t.Fatalf("schema = %+v", got)
	}
	if _, err := SchemaFromDDLMap(map[string]string{"bad": "ALTER TABLE users ADD COLUMN name TEXT;"}); err == nil {
		t.Fatal("expected invalid DDL to be rejected")
	}
	if _, err := SchemaFromDDLMap(map[string]string{
		"a": "CREATE TABLE users (id BIGINT);",
		"b": "CREATE TABLE users (name TEXT);",
	}); err == nil {
		t.Fatal("expected duplicate table to be rejected")
	} else if got := apperrors.AsAppError(err).Code; got != apperrors.CodeValidationFailed {
		t.Fatalf("duplicate error code = %s, want %s", got, apperrors.CodeValidationFailed)
	}
}

func TestClassifyDiffRisk(t *testing.T) {
	add := Change{Action: ActionAddColumn, Table: "users", Column: "name", Type: "VARCHAR(100)"}
	if risk, destructive := ClassifyChange(add); risk != RiskR1 || destructive {
		t.Fatalf("ClassifyChange(add) = %s/%t", risk, destructive)
	}
	modify := Change{Action: ActionModifyColumn, Table: "users", Column: "name", Type: "TEXT", Destructive: true}
	if risk, destructive := ClassifyChange(modify); risk != RiskR3 || !destructive {
		t.Fatalf("ClassifyChange(modify) = %s/%t", risk, destructive)
	}
	diff := DiffResult{Changes: []Change{add, modify}, Destructive: true}
	if classified := ClassifyDiff(diff); classified.OverallRisk != RiskR3 || !classified.Destructive {
		t.Fatalf("ClassifyDiff() = %+v", classified)
	}
}

func writeSchemaTestFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestSchemaModelCarriesIntrospectionDetails(t *testing.T) {
	def := "CURRENT_TIMESTAMP"
	table := Table{
		Name: "users",
		Columns: []Column{
			{Name: "id", Type: "BIGINT", Nullable: false, Key: "PRI"},
			{Name: "created_at", Type: "DATETIME", Nullable: true, Default: &def},
		},
		Indexes:     []Index{{Name: "idx_users_created_at", Columns: []string{"created_at"}, Unique: false}},
		ForeignKeys: []ForeignKey{{Name: "fk_users_org", Columns: []string{"org_id"}, RefTable: "orgs", RefColumns: []string{"id"}}},
	}
	if table.Columns[1].Default == nil || *table.Columns[1].Default != def {
		t.Fatalf("default not carried: %+v", table.Columns[1])
	}
	if table.Indexes[0].Columns[0] != "created_at" || table.ForeignKeys[0].RefTable != "orgs" {
		t.Fatalf("introspection details not carried: %+v", table)
	}
}
